export const attackCards = [];
export const organCards = [
  { id: "organ-001", name: "Appendix", type: "ORGAN", life: 2 },
  { id: "organ-002", name: "Bladder", type: "ORGAN", life: 2 },
  { id: "organ-003", name: "Bones", type: "ORGAN", life: 2 },
  { id: "organ-004", name: "Bowels", type: "ORGAN", life: 2 },
  { id: "organ-005", name: "Brain", type: "ORGAN", life: 2 },
  { id: "organ-006", name: "Esophagus", type: "ORGAN", life: 2 },
  { id: "organ-007", name: "Eyes", type: "ORGAN", life: 2 },
  { id: "organ-008", name: "Gallbladder", type: "ORGAN", life: 2 },
  { id: "organ-009", name: "Heart", type: "ORGAN", life: 2 },
  { id: "organ-010", name: "Kidneys", type: "ORGAN", life: 2 },
  { id: "organ-011", name: "Liver", type: "ORGAN", life: 2 },
  { id: "organ-012", name: "Lungs", type: "ORGAN", life: 2 },
  { id: "organ-013", name: "Nose", type: "ORGAN", life: 2 },
  { id: "organ-014", name: "Pancreas", type: "ORGAN", life: 2 },
  { id: "organ-015", name: "Skeletal Muscles", type: "ORGAN", life: 2 },
  { id: "organ-016", name: "Skin", type: "ORGAN", life: 2 },
  { id: "organ-017", name: "Spleen", type: "ORGAN", life: 2 },
  { id: "organ-018", name: "Stomach", type: "ORGAN", life: 2 },
  { id: "organ-019", name: "Teeth", type: "ORGAN", life: 2 },
  { id: "organ-020", name: "Thyroid", type: "ORGAN", life: 2 },
  { id: "organ-021", name: "Tongue", type: "ORGAN", life: 2 },
  { id: "organ-022", name: "Tonsils", type: "ORGAN", life: 2 },
  { id: "organ-023", name: "Trachea", type: "ORGAN", life: 2 },
  { id: "organ-024", name: "Wild", type: "ORGAN", life: 4 },
];
